"""Add tier and BYOK to User model

Revision ID: 052985d2bf04
Revises: bdd37ed72672
Create Date: 2024-07-26 14:27:34.773773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052985d2bf04'
down_revision: Union[str, Sequence[str], None] = 'bdd37ed72672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(), nullable=False, server_default='free'))
    op.add_column('users', sa.Column('encrypted_openai_api_key', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('encrypted_anthropic_api_key', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('encrypted_gemini_api_key', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('encrypted_groq_api_key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_groq_api_key')
    op.drop_column('users', 'encrypted_gemini_api_key')
    op.drop_column('users', 'encrypted_anthropic_api_key')
    op.drop_column('users', 'encrypted_openai_api_key')
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
